apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-premium
  csi:
    driver: file.csi.azure.com
    volumeHandle: "MC_aks-west_aks-west_westus#westdata#nfs"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      protocol: nfs
      storageAccount: bydbgpcaksrocketmq
      resourceGroup: BSOP-Pairs-RG  # optional, only set this when storage account is not in the same resource group as node
      shareName: sharednfs
  mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30