apiVersion: v1
kind: Service
metadata:
  name: myapp-clusterip
  namespace: default
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - port: 80  # Service端口       
    targetPort: 80 # pod端口
