apiVersion: v1
kind: Service
metadata:
  name: nodeport-81
spec:
  type: NodePort
  ports:
  - port: 81
    protocol: TCP
    targetPort: 80
  selector:
    run: testapp02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: testapp02
  name: testapp02
spec:
  replicas: 1
  selector:
    matchLabels:
      run: testapp02
  template:
    metadata:
      labels:
        run: testapp02
    spec:
      containers:
      - image: nginx
        name: nginx