apiVersion: apps/v1
kind: Deployment
metadata:
  name: scnginx-deployment
  labels:
    app: scnginx
spec:
  replicas: 9
  selector:
    matchLabels:
      app: scnginx
  template:
    metadata:
      labels:
        app: scnginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: scnginx-service
spec:
  type: NodePort    
  selector:
    app: scnginx
  ports:
  - name: nginx-svc-nodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
